teams = {
    "ARG": list(range(1, 21)),
    "BRA": list(range(1, 21)),
    "URU": list(range(1, 21)),
    "PAR": list(range(1, 21)),
    "COL": list(range(1, 21)),
    "ECU": list(range(1, 21)),
    "PER": list(range(1, 21)),
    "CHI": list(range(1, 21)),

    "USA": list(range(1, 21)),
    "CAN": list(range(1, 21)),
    "MEX": list(range(1, 21)),
    "CRC": list(range(1, 21)),
    "PAN": list(range(1, 21)),
    "HON": list(range(1, 21)),
    "JAM": list(range(1, 21)),

    "ENG": list(range(1, 21)),
    "FRA": list(range(1, 21)),
    "GER": list(range(1, 21)),
    "ESP": list(range(1, 21)),
    "POR": list(range(1, 21)),
    "ITA": list(range(1, 21)),
    "NED": list(range(1, 21)),
    "BEL": list(range(1, 21)),
    "CRO": list(range(1, 21)),
    "SUI": list(range(1, 21)),
    "DEN": list(range(1, 21)),
    "SWE": list(range(1, 21)),
    "NOR": list(range(1, 21)),
    "POL": list(range(1, 21)),
    "SRB": list(range(1, 21)),
    "AUT": list(range(1, 21)),
    "UKR": list(range(1, 21)),

    "MAR": list(range(1, 21)),
    "ALG": list(range(1, 21)),
    "TUN": list(range(1, 21)),
    "EGY": list(range(1, 21)),
    "SEN": list(range(1, 21)),
    "GHA": list(range(1, 21)),
    "CMR": list(range(1, 21)),
    "CIV": list(range(1, 21)),

    "JPN": list(range(1, 21)),
    "KOR": list(range(1, 21)),
    "IRN": list(range(1, 21)),
    "AUS": list(range(1, 21)),
    "KSA": list(range(1, 21)),
    "QAT": list(range(1, 21)),
    "UAE": list(range(1, 21))
}